apiVersion: apps/v1
kind: Deployment
metadata:
  name: miku
  namespace: vocaloid
  labels:
    app: miku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miku
  template:
    metadata:
      labels:
        app: miku
    spec:
      containers:
        - name: miku
          image: kix.ocir.io/nro0opflyunj/miku/miku:1b0acdd
          env:
            - name: NEO4J_URI
              valueFrom:
                secretKeyRef:
                  name: vocaloid-secret
                  key: neo4jURI
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vocaloid-secret
                  key: neo4jUsername
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vocaloid-secret
                  key: neo4jPassword
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ocirsecret
